server:
  port: 5000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   #开启自动发现
          lower-case-service-id: true #自动转成小写
      routes:   #路由数组
        - id: user-consumer
          uri: lb://user-consumer   #匹配的路径
          predicates:   #断言
            - Path=/user/**   #自动拼接到uri后面
          filters:
            - StripPrefix=1   #去除/user
        - id: goods-consumer
          uri: lb://goods-consumer
          predicates:
            - Path=/goods/**
          filters:
            - StripPrefix=1   #去除/goods
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/