server:
  port: 8893
spring:
  application:
    name: user-consumer
  thymeleaf:    # thymeleaf
    cache: false
    prefix: classpath:/template/
    suffix: .html
    encoding: UTF-8
eureka:         # eureka
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
feign:        # feign
  circuitbreaker:
    enabled: true