server:
  port: 8750
spring:
  application:
    name: goods-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/goods?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: tda6060g
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8500/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:/mapper/*